# Generated by Django 3.1.6 on 2021-02-16 01:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='finishDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
