# Generated by Django 3.1.6 on 2021-02-24 05:57

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0004_auto_20210223_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=tinymce.models.HTMLField(verbose_name={'menubar': 'insert edit view', 'plugins': 'lists advlist autosave charmap codesample hr image imagetools media paste preview', 'theme': 'modern', 'toolbar': 'codesample charmap hr image media paste pastetext preview'}),
        ),
    ]
