# Generated by Django 3.1.6 on 2021-02-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0009_auto_20210224_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='subtopic',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
