# Generated by Django 3.1.6 on 2021-02-16 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_finishdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='finishDate',
            new_name='finish',
        ),
    ]
