# Generated by Django 3.1.6 on 2021-02-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20210215_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='finish',
            field=models.DateField(),
        ),
    ]
